apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod
  name: pod
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - echo hello; sleep 3600
    image: busybox
    name: c1
    resources: {}
  - command:
    - /bin/sh
    - -c
    - echo hello; sleep 3600
    image: busybox
    name: c2
  restartPolicy: Never
status: {}
