apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod
  name: pod
spec:
  containers:
  - image: nginx
    name: pod
    resources: {}
    volumeMounts:
    - name: vol
      mountPath: /etc/foo
  volumes:
  - name: vol
    secret:
      secretName: mysecret2
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
