apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod
  name: pod
spec:
  containers:
  - image: nginx
    name: pod
    resources: {}
    env:
      - name: USERNAME
        valueFrom:
          secretKeyRef: 
            name: mysecret2
            key: username
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
