apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - args:
    - sleep
    - "3600"
    image: busybox
    name: c1
    resources: {}
    volumeMounts:
    - mountPath: /etc/foo
      name: vol
  - image: busybox
    args:
    - sleep
    - "3600"
    name: c2
    volumeMounts:
    - mountPath: /etc/foo
      name: vol
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: vol
    emptyDir: {}
status: {}
