apiVersion: v1
kind: PersistentVolume
metadata:
  name: myvolume
spec:
  capacity: 
    storage: 10Gi
  storageClassName: "normal"
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  hostPath: 
    path: "/etc/foo"
