apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - args:
    - sleep
    - "3600"
    image: busybox
    name: busybox
    resources: {}
    volumeMounts:
    - mountPath: /etc/foo
      name: vol
  restartPolicy: Never
  volumes:
    - name: vol
      persistentVolumeClaim:
        claimName: mypvc
status: {}
