apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: job
spec:
  activeDeadlineSeconds: 30
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - echo hello;sleep 30;echo world
        image: busybox
        name: job
        resources: {}
      restartPolicy: Never
status: {}
